import Nav from './auth/nav'
import './globals.css'
import type { Metadata } from 'next'
import {Roboto} from "next/font/google";

const roboto= Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto"
})

export const metadata: Metadata = {
  title: 'Post It',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang='en'>
			<body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-gray-200`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
